// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Em Prisma 7 não existe mais `directUrl` separado: o runtime usa o pooler
// via adapter (ver `src/utils/db.ts`), e o `url` daqui é só para `prisma migrate`.
// Por isso usamos DIRECT_URL (porta 5432) que suporta DDL/prepared statements.
const migrateUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
if (!migrateUrl) {
  throw new Error("DIRECT_URL (preferido) ou DATABASE_URL precisa estar setado");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl,
  },
});
