// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { env } from "./src/config/env";

// Em Prisma 7 não existe mais `directUrl` separado: o runtime usa o pooler
// via adapter (ver `src/utils/db.ts`), e o `url` daqui é só para `prisma migrate`.
// Por isso usamos DIRECT_URL (porta 5432) que suporta DDL/prepared statements.
const migrateUrl = env.DIRECT_URL ?? env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl,
  },
});
